- name: install unzip and aptitude
  package:
    name: 
    - unzip
    - aptitude
    state: latest
    update_cache: true

- name: Install required system packages
  package:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
    state: latest
    update_cache: true