---
- name: update and install packages
  hosts: parent
  pre_tasks:
  
  - name: install updates
    package:
      update_cache: yes
      state: latest

  - name: install packages
    package:
      name:
        - "{{ php }}"
        - python3
        - python3-pip
        - python3-setuptools
        - curl
      state: latest
      update_cache: true


- name: setup apache and deploy web page
  hosts: parent
  roles:
  - setup_apache
  - deploy_webpage


- name: install work-tools on webservers
  hosts: webservers
  roles:
  - install_dependencies
  - install_jenkins
  - install_terraform
  - install_docker
