- name: install openJDK Java
  package:
    name: openjdk-11-jre
    update_cache: yes

- name: install Jenkins apt-repo key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    state: present

- name: install Jenkins repo
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: install Jenkins
  package:
    name: jenkins
    update_cache: yes

- name: start Jenkins
  service:
    name: jenkins
    state: started
    enabled: true

- name: Allow all access to port 8080
  community.general.ufw:
    rule: allow
    port: '8080'
